name: "Netbird Client"
version: "0.23.9-1"
slug: netbird_client
description: >-
  Netbird client addon for Home Assistant
arch:
 - aarch64
url: "https://github.com/glemsom/hassio-netbird"
map:
  - config:rw
  - ssl
init: false
host_network: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
devices:
  - /dev/net/tun
options:
  SETUP_KEY: ""
  CONFIG_FILE: /config/netbird/config.json
schema:
  SETUP_KEY: str?
  CONFIG_FILE: str
image: "ghcr.io/glemsom/{arch}-netbird-client"
