name: "NetBird Client"
version: "0.25.4-1"
slug: netbird_client
description: >-
  WireGuard®-based mesh network with SSO/MFA support.
  Free and easy to setup and maintain.
arch:
  - aarch64
  - amd64
  - armhf
  - i386
url: "https://github.com/glemsom/hassio-netbird"
map:
  - config:rw
  - ssl
init: false
host_network: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
devices:
  - /dev/net/tun
options:
  log_level: info
schema:
  setup_key: str?
  config_file: str?
  admin_url: str?
  management_url: str?
  log_level: list(info|warning|error|trace|debug)
image: "ghcr.io/glemsom/{arch}-netbird-client"
